source 'https://github.com/CocoaPods/Specs.git'
target 'Trends' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  pod ‘OCMock’
  pod 'Masonry'
	
  target 'TrendsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

